---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- bench/bench.md is generated from bench/bench.Rmd. Please edit that file -->

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "bench/figures/bench-",
  out.width = "100%",
  fig.height = 6,
  code.fold = TRUE,
  collapse = TRUE
)
```

```{r}
#| label: packages-functions
fuj::require_namespace("bench")
fuj::require_namespace("stringi")
fuj::require_namespace("ggplot2")
fuj::require_namespace("ggbeeswarm")
fuj::require_namespace("gt")

library(facts)
library(forcats, include.only = "as_factor")

# assuming it's the same as numeric
as_factor.Date <- function(x, ...) {
  factor(x)
}

registerS3method("as_factor", "Date", as_factor.Date)
```

```{r}
#| label: functions
f_plot <- function(x) {
  x$expression <- as.character(x$expression)
  # x$median <- log1p(x$median)
  # x <- tidyr::unnest(x, c(time, gc))
  # x$n_unique <- factor(x$n_unique)
  # x$n_values <- factor(x$n_values)
  ggplot2::ggplot(
    x, 
    ggplot2::aes(
      x = .data[["n_values"]],
      y = .data[["median"]],
      col = .data[["expression"]],
      group = .data[["expression"]]
    )
  ) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::scale_x_continuous(
      trans = "log1p",
      breaks = 10^(2:6)
    ) +
    ggplot2::scale_y_continuous(trans = "log1p") +
    ggplot2::coord_trans("log1p", "log1p") +
    ggplot2::theme_light() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
    ) +
    ggplot2::facet_grid(
      cols = ggplot2::vars(n_unique),
      rows = ggplot2::vars(value_type),
      scales = "free"
    ) +
    ggplot2::labs(
      x = "number of values",
      y = "median time",
      col = "function",
      title = "Median times across types and unique values"
    )
}
```


## Benchmarks

### Logical

Logical vectors are by far speediest as `fact()` does not need to retrieve unique values, instead using both `TRUE` and `FALSE` values by default, and quickly looking for `NA` values.

```{r}
#| label: bench-logical
res <- bench::press(
  n_unique = 3,
  n_values = 10^(2:6),
  value_type = "logical",
  {
    x <- sample(c(TRUE, FALSE, NA), n_values, TRUE)
    bench::mark(
      factor = factor(x),
      forcats = as_factor(x),
      fact = fact(x),
      check = FALSE
    )
  }
)
```

```{r}
#| label: table-logical
res[1:9] |> 
  transform(expression = sapply(expression, deparse1)) |> 
  gt::gt("expression", "value_type") |> 
  gt::tab_options(row.striping.include_table_body = TRUE)
```

```{r}
#| label: plot-logical
f_plot(res)
```

```{r}
#| label: auto-plot-logical
ggplot2::autoplot(res)
```


## Other types

```{r}
#| label: bench-others
res <- bench::press(
  n_unique = 10^(1:4),
  n_values = 10^(2:6),
  value_type = c("character", "double", "integer", "date"),
  {
    x <- switch(
      value_type,
      character = stringi::stri_rand_strings(n_unique, 5),
      double = seq_len(n_unique) / n_unique,
      integer = seq_len(n_unique),
      date = Sys.Date() + seq_len(n_unique),
      stop("Unknown value typeL ", value_type)
    )
    x <- sample(x, n_values, TRUE)
    bench::mark(
      factor = factor(x),
      forcats = as_factor(x),
      fact = fact(x),
      check = FALSE
    )
  }
)
```

```{r}
#| label: table-others
res[1:9] |> 
  transform(expression = sapply(expression, deparse1)) |> 
  gt::gt("expression", "value_type") |> 
  gt::tab_options(row.striping.include_table_body = TRUE)
```


```{r}
#| label: plot-others
#| fig-width: 12
#| fig-height: 12
f_plot(res)
```

```{r}
#| label: auto-plot-others
#| fig-width: 12
#| fig-height: 12
ggplot2::autoplot(res)
```
